stages:
  - build
  - test

build:osx:
  stage: build
  script:
     - mkdir build
     - cd build
     - cmake -GXcode ..
     - cmake --build . --config Debug
     - cp Debug/mzn2fzn Debug/mzn-fzn Debug/solns2out ../
  artifacts:
     paths:
       - mzn2fzn
       - mzn-fzn
       - solns2out
     expire_in: 2h
  only:
     - develop
  tags:
     - mac

build:linux:
  image: guidotack/build-minizinc:1.0
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - cp mzn2fzn mzn-fzn solns2out ../
  artifacts:
     paths:
       - mzn2fzn
       - mzn-fzn
       - solns2out
     expire_in: 2h
  only:
     - develop
  tags:
     - linux

test:mzn20_fd:osx:
  stage: test
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn20_fd .mzn unit examples
  dependencies:
     - build:osx
  only:
     - develop
  tags:
     - mac

test:mzn-fzn_fd:osx:
  stage: test
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn-fzn_fd .mzn unit examples
  dependencies:
     - build:osx
  only:
     - develop
  tags:
     - mac


test:mzn20_fd:linux:
  image: guidotack/build-minizinc:1.0
  stage: test
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn20_fd .mzn unit examples
  dependencies:
     - build:linux
  only:
     - develop
  tags:
     - linux

test:mzn-fzn_fd:linux:
  image: guidotack/build-minizinc:1.0
  stage: test
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn-fzn_fd .mzn unit examples
  dependencies:
     - build:linux
  only:
     - develop
  tags:
     - linux

